package com.sunkaisens.nms.ws.createFile.client.alarm;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "AlarmManageWebService", targetNamespace = "http://AlarmManage.webservice.com")
public interface AlarmManageWebService {

	/**
	 * 
	 * @param arg0
	 * @return returns boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "http://AlarmManage.webservice.com")
	@RequestWrapper(localName = "rptAlarm", targetNamespace = "http://AlarmManage.webservice.com", className = "com.sunkaisens.ni.ws.alarm.RptAlarm")
	@ResponseWrapper(localName = "rptAlarmResponse", targetNamespace = "http://AlarmManage.webservice.com", className = "com.sunkaisens.ni.ws.alarm.RptAlarmResponse")
	public boolean rptAlarm(
			@WebParam(name = "arg0", targetNamespace = "http://AlarmManage.webservice.com") String arg0);

}
