package com.sunkaisens.nms.ws.createFile.client.heart;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "HeartBeatWebService", targetNamespace = "http://HeartBeat.webservice.com")
public interface HeartBeatWebService {

	/**
	 * 
	 * @param arg0
	 * @return returns boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "http://HeartBeat.webservice.com")
	@RequestWrapper(localName = "rptHeartBeat", targetNamespace = "http://HeartBeat.webservice.com", className = "HeartBeat.webservice.com.RptHeartBeat")
	@ResponseWrapper(localName = "rptHeartBeatResponse", targetNamespace = "http://HeartBeat.webservice.com", className = "HeartBeat.webservice.com.RptHeartBeatResponse")
	public boolean rptHeartBeat(
			@WebParam(name = "arg0", targetNamespace = "http://HeartBeat.webservice.com") String arg0);

}
