package com.sunkaisens.nms.ws.createFile.client.equip;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "DevManageWebService", targetNamespace = "http://DevManage.webservice.com")
public interface DevManageWebService {

	/**
	 * 
	 * @param arg0
	 * @return returns boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "http://DevManage.webservice.com")
	@RequestWrapper(localName = "rptDevInfo", targetNamespace = "http://DevManage.webservice.com", className = "com.sunkaisens.ni.ws.equip.RptDevInfo")
	@ResponseWrapper(localName = "rptDevInfoResponse", targetNamespace = "http://DevManage.webservice.com", className = "com.sunkaisens.ni.ws.equip.RptDevInfoResponse")
	public boolean rptDevInfo(
			@WebParam(name = "arg0", targetNamespace = "http://DevManage.webservice.com") String arg0);

}
