package com.sunkaisens.nms.ws.createFile.client.log;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "LogManageWebService", targetNamespace = "http://LogManage.webservice.com")
public interface LogManageWebService {

	/**
	 * 
	 * @param arg0
	 * @return returns boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "http://LogManage.webservice.com")
	@RequestWrapper(localName = "rptLog", targetNamespace = "http://LogManage.webservice.com", className = "com.sunkaisens.ni.ws.log.RptLog")
	@ResponseWrapper(localName = "rptLogResponse", targetNamespace = "http://LogManage.webservice.com", className = "com.sunkaisens.ni.ws.log.RptLogResponse")
	public boolean rptLog(
			@WebParam(name = "arg0", targetNamespace = "http://LogManage.webservice.com") String arg0);

}
