package com.sunkaisens.nms.ws.createFile.client.route;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "RoutingWebService", targetNamespace = "http://Routing.webservice.com")
public interface RoutingWebService {

	/**
	 * 
	 * @param arg0
	 * @return returns boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "http://Routing.webservice.com")
	@RequestWrapper(localName = "rptRoutingInfo", targetNamespace = "http://Routing.webservice.com", className = "com.sunkaisens.ni.ws.route.RptRoutingInfo")
	@ResponseWrapper(localName = "rptRoutingInfoResponse", targetNamespace = "http://Routing.webservice.com", className = "com.sunkaisens.ni.ws.route.RptRoutingInfoResponse")
	public boolean rptRoutingInfo(
			@WebParam(name = "arg0", targetNamespace = "http://Routing.webservice.com") String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "http://Routing.webservice.com")
	@RequestWrapper(localName = "rstTermInfo", targetNamespace = "http://Routing.webservice.com", className = "com.sunkaisens.ni.ws.route.RstTermInfo")
	@ResponseWrapper(localName = "rstTermInfoResponse", targetNamespace = "http://Routing.webservice.com", className = "com.sunkaisens.ni.ws.route.RstTermInfoResponse")
	public boolean rstTermInfo(
			@WebParam(name = "arg0", targetNamespace = "http://Routing.webservice.com") String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "http://Routing.webservice.com")
	@RequestWrapper(localName = "rstRoutingInfo", targetNamespace = "http://Routing.webservice.com", className = "com.sunkaisens.ni.ws.route.RstRoutingInfo")
	@ResponseWrapper(localName = "rstRoutingInfoResponse", targetNamespace = "http://Routing.webservice.com", className = "com.sunkaisens.ni.ws.route.RstRoutingInfoResponse")
	public boolean rstRoutingInfo(
			@WebParam(name = "arg0", targetNamespace = "http://Routing.webservice.com") String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "http://Routing.webservice.com")
	@RequestWrapper(localName = "rptRoutingMsg", targetNamespace = "http://Routing.webservice.com", className = "com.sunkaisens.ni.ws.route.RptRoutingMsg")
	@ResponseWrapper(localName = "rptRoutingMsgResponse", targetNamespace = "http://Routing.webservice.com", className = "com.sunkaisens.ni.ws.route.RptRoutingMsgResponse")
	public boolean rptRoutingMsg(
			@WebParam(name = "arg0", targetNamespace = "http://Routing.webservice.com") String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "http://Routing.webservice.com")
	@RequestWrapper(localName = "rstKeyDef", targetNamespace = "http://Routing.webservice.com", className = "com.sunkaisens.ni.ws.route.RstKeyDef")
	@ResponseWrapper(localName = "rstKeyDefResponse", targetNamespace = "http://Routing.webservice.com", className = "com.sunkaisens.ni.ws.route.RstKeyDefResponse")
	public boolean rstKeyDef(
			@WebParam(name = "arg0", targetNamespace = "http://Routing.webservice.com") String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "http://Routing.webservice.com")
	@RequestWrapper(localName = "rptKeyDef", targetNamespace = "http://Routing.webservice.com", className = "com.sunkaisens.ni.ws.route.RptKeyDef")
	@ResponseWrapper(localName = "rptKeyDefResponse", targetNamespace = "http://Routing.webservice.com", className = "com.sunkaisens.ni.ws.route.RptKeyDefResponse")
	public boolean rptKeyDef(
			@WebParam(name = "arg0", targetNamespace = "http://Routing.webservice.com") String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "http://Routing.webservice.com")
	@RequestWrapper(localName = "rptTermInfo", targetNamespace = "http://Routing.webservice.com", className = "com.sunkaisens.ni.ws.route.RptTermInfo")
	@ResponseWrapper(localName = "rptTermInfoResponse", targetNamespace = "http://Routing.webservice.com", className = "com.sunkaisens.ni.ws.route.RptTermInfoResponse")
	public boolean rptTermInfo(
			@WebParam(name = "arg0", targetNamespace = "http://Routing.webservice.com") String arg0);

}
