package com.sunkaisens.nms.ws.createFile.client.perf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "PerfManageWebService", targetNamespace = "http://PerfManage.webservice.com")
public interface PerfManageWebService {

	/**
	 * 
	 * @param arg0
	 * @return returns boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "http://PerfManage.webservice.com")
	@RequestWrapper(localName = "rptPerf", targetNamespace = "http://PerfManage.webservice.com", className = "com.sunkaisens.ni.ws.perf.RptPerf")
	@ResponseWrapper(localName = "rptPerfResponse", targetNamespace = "http://PerfManage.webservice.com", className = "com.sunkaisens.ni.ws.perf.RptPerfResponse")
	public boolean rptPerf(
			@WebParam(name = "arg0", targetNamespace = "http://PerfManage.webservice.com") String arg0);

}
