package com.sunkaisens.nms.ws.createFile.client.perf;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * PerfManage_Service service = new PerfManage_Service();
 * PerfManageWebService portType = service.getPerfManageEndPoint();
 * portType.rptPerf(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "PerfManage_Service", targetNamespace = "http://PerfManage.webservice.com", wsdlLocation = "file:/F:/\u9879\u76ee/1510/\u63a5\u53e3\u6587\u6863/\u5317\u5411\u63a5\u53e3\u5f00\u53d1\u8ddf\u8e2a/wsdl-20171112/PerfManage_Service.xml")
public class PerfManageService extends Service {

	private final static URL PERFMANAGESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.sunkaisens.nms.ws.createFile.client.perf.PerfManageService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.sunkaisens.nms.ws.createFile.client.perf.PerfManageService.class
					.getResource(".");
			url = new URL(
					baseUrl,
					"file:/F:/\u9879\u76ee/1510/\u63a5\u53e3\u6587\u6863/\u5317\u5411\u63a5\u53e3\u5f00\u53d1\u8ddf\u8e2a/wsdl-20171112/PerfManage_Service.xml");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'file:/F:/\u9879\u76ee/1510/\u63a5\u53e3\u6587\u6863/\u5317\u5411\u63a5\u53e3\u5f00\u53d1\u8ddf\u8e2a/wsdl-20171112/PerfManage_Service.xml', retrying as a local file");
			logger.warning(e.getMessage());
		}
		PERFMANAGESERVICE_WSDL_LOCATION = url;
	}

	public PerfManageService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public PerfManageService() {
		super(PERFMANAGESERVICE_WSDL_LOCATION, new QName(
				"http://PerfManage.webservice.com", "PerfManage_Service"));
	}

	/**
	 * 
	 * @return returns PerfManageWebService
	 */
	@WebEndpoint(name = "PerfManage-EndPoint")
	public PerfManageWebService getPerfManageEndPoint() {
		return super.getPort(new QName("http://PerfManage.webservice.com",
				"PerfManage-EndPoint"), PerfManageWebService.class);
	}

}
